# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 757)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_20 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_20.setObjectName("toolButton_20")
        self.gridLayout.addWidget(self.toolButton_20, 0, 0, 1, 1)
        self.toolButton_21 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_21.setObjectName("toolButton_21")
        self.gridLayout.addWidget(self.toolButton_21, 0, 1, 1, 1)
        self.toolButton_22 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_22.setObjectName("toolButton_22")
        self.gridLayout.addWidget(self.toolButton_22, 0, 2, 1, 1)
        self.toolButton_23 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_23.setObjectName("toolButton_23")
        self.gridLayout.addWidget(self.toolButton_23, 0, 3, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 0, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 1, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.frame_4)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 2, 1, 1)
        self.toolButton_15 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_15.setObjectName("toolButton_15")
        self.gridLayout.addWidget(self.toolButton_15, 1, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.imgFrame = QtWidgets.QFrame(self.centralwidget)
        self.imgFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.imgFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgFrame.setObjectName("imgFrame")
        self.verticalLayout_4.addWidget(self.imgFrame)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolButton_19 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_19.setObjectName("toolButton_19")
        self.gridLayout_2.addWidget(self.toolButton_19, 0, 0, 1, 1)
        self.toolButton_18 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_18.setObjectName("toolButton_18")
        self.gridLayout_2.addWidget(self.toolButton_18, 0, 1, 1, 1)
        self.toolButton_17 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_17.setObjectName("toolButton_17")
        self.gridLayout_2.addWidget(self.toolButton_17, 0, 2, 1, 1)
        self.toolButton_16 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_16.setObjectName("toolButton_16")
        self.gridLayout_2.addWidget(self.toolButton_16, 0, 3, 1, 1)
        self.toolButton_14 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_14.setObjectName("toolButton_14")
        self.gridLayout_2.addWidget(self.toolButton_14, 0, 4, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_2.addWidget(self.toolButton_8, 1, 0, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout_2.addWidget(self.toolButton_11, 1, 1, 1, 1)
        self.toolButton_13 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_13.setObjectName("toolButton_13")
        self.gridLayout_2.addWidget(self.toolButton_13, 1, 2, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout_2.addWidget(self.toolButton_12, 1, 3, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout_2.addWidget(self.toolButton_10, 1, 4, 1, 1)
        self.toolButton_8.raise_()
        self.toolButton_10.raise_()
        self.toolButton_11.raise_()
        self.toolButton_12.raise_()
        self.toolButton_13.raise_()
        self.toolButton_16.raise_()
        self.toolButton_14.raise_()
        self.toolButton_17.raise_()
        self.toolButton_18.raise_()
        self.toolButton_19.raise_()
        self.verticalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 10)
        self.verticalLayout_4.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.fileDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.fileDockWidget.setFloating(False)
        self.fileDockWidget.setObjectName("fileDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileListWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.fileListWidget.setObjectName("fileListWidget")
        self.verticalLayout.addWidget(self.fileListWidget)
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 5)
        self.fileDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.fileDockWidget)
        self.labelDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.labelDockWidget.setObjectName("labelDockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelFrame = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.labelFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.labelFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelFrame.setObjectName("labelFrame")
        self.verticalLayout_2.addWidget(self.labelFrame)
        self.labelDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.labelDockWidget)
        self.typeDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.typeDockWidget.setObjectName("typeDockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget_2 = QtWidgets.QListWidget(self.dockWidgetContents_3)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget_2)
        self.listWidget_3 = QtWidgets.QListWidget(self.dockWidgetContents_3)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget_3)
        self.horizontalLayout.setStretch(1, 4)
        self.typeDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.typeDockWidget)
        self.editDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.editDockWidget.setObjectName("editDockWidget")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelEditFrame = QtWidgets.QFrame(self.dockWidgetContents_4)
        self.labelEditFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.labelEditFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelEditFrame.setObjectName("labelEditFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.labelEditFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.labelEditFrame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.labelEditFrame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.labelEditFrame)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.labelEditFrame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.labelEditFrame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.labelEditFrame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.labelEditFrame)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.labelEditFrame)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.labelEditFrame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.labelEditFrame)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 4, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.labelEditFrame)
        self.spinBox.setMaximum(1000000)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 1, 1, 1, 2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.labelEditFrame)
        self.spinBox_2.setMaximum(1000000)
        self.spinBox_2.setDisplayIntegerBase(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 2, 1, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 2)
        self.gridLayout_3.setColumnStretch(1, 5)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.verticalLayout_3.addWidget(self.labelEditFrame)
        self.editDockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.editDockWidget)
        self.typeDockWidget.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_20.setText(_translate("MainWindow", "编辑"))
        self.toolButton_21.setText(_translate("MainWindow", "画框"))
        self.toolButton_22.setText(_translate("MainWindow", "打码"))
        self.toolButton_23.setText(_translate("MainWindow", "恢复原图"))
        self.toolButton_2.setText(_translate("MainWindow", "还原文件"))
        self.toolButton_4.setText(_translate("MainWindow", "丢弃文件"))
        self.toolButton.setText(_translate("MainWindow", "删除当前文件"))
        self.toolButton_15.setText(_translate("MainWindow", "保存结果"))
        self.toolButton_19.setText(_translate("MainWindow", "拷贝"))
        self.toolButton_18.setText(_translate("MainWindow", "删除"))
        self.toolButton_17.setText(_translate("MainWindow", "粘贴"))
        self.toolButton_16.setText(_translate("MainWindow", "复制"))
        self.toolButton_14.setText(_translate("MainWindow", "撤回"))
        self.toolButton_8.setText(_translate("MainWindow", "上一个"))
        self.toolButton_11.setText(_translate("MainWindow", "待编辑"))
        self.toolButton_13.setText(_translate("MainWindow", "待丢弃"))
        self.toolButton_12.setText(_translate("MainWindow", "完成"))
        self.toolButton_10.setText(_translate("MainWindow", "下一个"))
        self.fileDockWidget.setWindowTitle(_translate("MainWindow", "文件列表"))
        self.lineEdit.setText(_translate("MainWindow", "查找"))
        self.label_2.setText(_translate("MainWindow", "已完成：20   20%"))
        self.label_3.setText(_translate("MainWindow", "待丢弃：1   1%"))
        self.label_4.setText(_translate("MainWindow", "标注用时： 2min 30s"))
        self.label_5.setText(_translate("MainWindow", "完成时间：----"))
        self.labelDockWidget.setWindowTitle(_translate("MainWindow", "标签列表"))
        self.typeDockWidget.setWindowTitle(_translate("MainWindow", "标签类别"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "car"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "bus"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "多边形"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "矩形"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.editDockWidget.setWindowTitle(_translate("MainWindow", "标签编辑"))
        self.pushButton.setText(_translate("MainWindow", "类别:"))
        self.label_9.setText(_translate("MainWindow", "id："))
        self.label_10.setText(_translate("MainWindow", "异常属性："))
        self.label_11.setText(_translate("MainWindow", "车牌号"))
        self.label_12.setText(_translate("MainWindow", "车牌颜色"))
